---
kubernetes_node_packages:
  - containerd
  - gpg

kubernetes_node_kernel_modules:
  - overlay
  - br_netfilter

kubernetes_node_sysctl_parameters:
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"
  net.ipv4.ip_forward: "1"

kubernetes_node_kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl

kubernetes_node_kubernetes_package_version: >-
  {{ kubernetes_version }}-{{ kubernetes_package_revision }}
