all:
  children:
    ansible_controllers:
      hosts:
        localhost:
          ansible_connection: local

    control_plane:
      hosts:
        k8s-cp-01:
          ansible_host: 192.168.0.221

    workers:
      hosts:
        k8s-worker-01:
          ansible_host: 192.168.0.222

        k8s-worker-02:
          ansible_host: 192.168.0.223

    k8s_cluster:
      children:
        control_plane:
        workers:

