---
kubernetes_control_plane_kubeadm_config_path: /etc/kubernetes/kubeadm-init.yaml

kubernetes_control_plane_admin_user: devops
kubernetes_control_plane_admin_group: devops
kubernetes_control_plane_admin_home: /home/devops

kubernetes_control_plane_admin_kubeconfig_source: /etc/kubernetes/admin.conf
kubernetes_control_plane_admin_kubeconfig_directory: >-
  {{ kubernetes_control_plane_admin_home }}/.kube
kubernetes_control_plane_admin_kubeconfig_path: >-
  {{ kubernetes_control_plane_admin_kubeconfig_directory }}/config
kubernetes_control_plane_bootstrap_enabled: false
